[project]
name = "bultrowicz-com"
version = "0.1.0"
description = "The personal website of Michał Bultrowicz"
authors = [{ name = "Michal Bultrowicz", email = "michal.bultrowicz@gmail.com" }]
license = "MIT"
requires-python = "~=3.11.0"
dependencies = [
    "lektor>=3.3.14",
    # used by the Lektor plugin in packages/ and to generate the syntax highlighting CSS
    "pygments>=2.21.0",
    # for building the CV PDF
    "playwright>=1.35.0",
]
