---
- name: deploy blog
  hosts: web
  remote_user: butla
  vars:
    repo_name: bultrowicz.com
    repo_dir: "{{ ansible_env.HOME }}/{{ repo_name }}"
    virtualenv_dir: "{{ ansible_env.HOME }}/blog_venv"

  tasks:
  - name: clone the blog
    git: repo=https://github.com/butla/{{ repo_name }}
         dest={{ repo_dir }}

  - name: prepare virtualenv for the blog
    pip:
      requirements: "{{ repo_dir }}/requirements.txt"
      virtualenv: "{{ virtualenv_dir }}"
      virtualenv_python: "python3.5"

  - name: build the blog
    command: "{{ virtualenv_dir }}/bin/ablog build"
    args:
      chdir: "{{ repo_dir }}"
  
  - name: copy blog to Nginx
    synchronize:
      src: "{{ repo_dir }}/_website/"
      dest: /var/www/html
      delete: yes
    delegate_to: "{{ inventory_hostname }}"
    become: true

