---
- name: deploy blog
  hosts: web
  remote_user: butla
  vars:
    repo_name: bultrowicz.com
    repo_dir: "{{ ansible_env.HOME }}/{{ repo_name }}"
    virtualenv_dir: "{{ ansible_env.HOME }}/blog_venv"

  tasks:
    - name: update the server
      apt: update_cache=yes upgrade=safe
      become: true

    - name: clone the blog
      git: repo=https://github.com/butla/{{ repo_name }}
           dest={{ repo_dir }}

    - name: prepare virtualenv for the blog
      pip:
        requirements: "{{ repo_dir }}/requirements.txt"
        virtualenv: "{{ virtualenv_dir }}"
        virtualenv_python: "python3.6"

    - name: build the blog
      command: "{{ virtualenv_dir }}/bin/ablog build"
      args:
        chdir: "{{ repo_dir }}"
      register: build_result
      changed_when: build_result.stdout.find("no targets are out of date") == -1

    - name: copy my terms to the built website pages
      synchronize:
        src: "{{ repo_dir }}/additional_pages/terms_of_working_with_me"
        dest: "{{ repo_dir }}/_website/"
      delegate_to: "{{ inventory_hostname }}"

    - name: copy blog to Nginx folder
      synchronize:
        src: "{{ repo_dir }}/_website/"
        dest: /var/www/html
        delete: yes
      delegate_to: "{{ inventory_hostname }}"
      become: true
