title = Butlablog
author = Michał "Butla" Bultrowicz
logo = /_static/butla_2.png
description = A blog about Python, software development and Linux.
copyright_since = 2016
# Comments. The thread identifiers ("/<post-slug>/") and URLs match the ones from the old ABlog site.
disqus_shortname = bultrowicz-com
